Preloader Added
tsparticles/404-templates pull request #52
Opened 2022-10-08 05:02 UTC by YashBawa

Fixed Issue #48
Preloader Added by adding code to Html and Css.
No other files were made changes . 
The preloader is working properly, animation created using Vanilla CSS
Reference of the work 
before:
![image](https://user-images.githubusercontent.com/90853282/194689353-608f4090-c31d-4f36-be29-1f926a06842b.png)
after 
![image](https://user-images.githubusercontent.com/90853282/194689390-8ae8c1e0-a369-4ee7-9eb3-ced8dafba0a4.png)
![image](https://user-images.githubusercontent.com/90853282/194689406-335f0b0e-96d1-40e4-a2c1-aa0b6aa1cbef.png)
Animation is working well , to get a better view please locally.
The color Theme of the preloader matches with the color theme of website.

2022-10-08 05:02 UTC, YashBawa commented
@matteobruni please review and verify it.
Thanks!!

2022-10-08 09:32 UTC, matteobruni requested changes
I've added some notes to the code, please review all of them

2022-10-08 09:32 UTC, matteobruni commented on index.html
> +  <!-- PRELOADER JS-->
Please remove comments from the HTML

2022-10-08 09:32 UTC, matteobruni commented on index.html
> +  <!-- preloader script tag -->
Please remove comments from the HTML

2022-10-08 09:32 UTC, matteobruni commented on index.html
> +  <!--preloader JS -->
Please remove comments from the HTML

2022-10-08 09:32 UTC, matteobruni commented on index.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
jQuery is already included below, please remove this

2022-10-08 09:32 UTC, matteobruni commented on index.html
> +  <script>
Move this JavaScript code, without comments, in the `js/main.js` file, or create a `js/preloader.js` file and include it in the page.

2022-10-08 09:32 UTC, matteobruni commented on index.html
> +      var preloader = $('.loader_bg');
This code is not properly formatted, please fix it.

2022-10-08 11:19 UTC, YashBawa commented
@matteobruni  I have commited with new changes please check and tell if any more issues needs to be resolved.

2022-10-08 12:18 UTC, matteobruni requested changes
Still one change needed

2022-10-08 12:18 UTC, matteobruni commented on js/main.js
> +$(document).ready(function()
There’s already a document ready function, please merge them together

2022-10-08 17:31 UTC, YashBawa commented
@matteobruni fixed all issues hope it's fine, if any other changes are needed then please notify!!

2022-10-09 11:12 UTC, matteobruni requested changes
I've seen that the preloaded has always 3 seconds of fadeOut, but it should be hidden once the AJAX request is completed. The AJAX request could take milliseconds or seconds, depending on the user browser and connection speed.
The animation is good anyway.

2022-10-09 12:48 UTC, YashBawa commented
Keeping a fixed time would be better, because as you mentioned if it takes only milliseconds then the preloader would not look proper and would look more like just an added page for a short while.

2022-10-09 13:37 UTC, matteobruni commented
> Keeping a fixed time would be better, because as you mentioned if it takes only milliseconds then the preloader would not look proper and would look more like just an added page for a short while.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/176620/194759941-90a04215-ee04-4eaf-a657-1267c3e55ea3.png">

I need 31ms seconds to complete the AJAX request, waiting the full 3 seconds is a waste of time. It's a simple site that loads a JSON file, the loader should be visible only while that request is still processing.

2022-10-10 12:36 UTC, YashBawa commented
Ok will add according

2022-11-03 13:03 UTC, closed without merging