feat: add glitter 404 template
tsparticles/404-templates pull request #75
Opened 2022-10-23 00:48 UTC by LeidiFlores

## Added Glitter theme! 

![image](https://user-images.githubusercontent.com/62189355/197367825-ccc92916-77ec-4660-ae38-b21e4af9cae6.png)

2022-10-23 00:53 UTC, matteobruni requested changes
Please read carefully #18, you didn't update a required file.

2022-10-23 00:58 UTC, LeidiFlores commented
I already added it, please check again @matteobruni

2022-10-23 01:02 UTC, matteobruni requested changes
Please check the theme using the main index.html, is not working on this PR.

2022-10-23 01:06 UTC, LeidiFlores commented
sorry, I missed a comma, it's ready now :)

2022-10-27 06:44 UTC, matteobruni requested changes
This configuration is really similar to the `ocean` one: https://tsparticles.github.io/404-templates/ocean/404.html

Please make it different, the noticeable difference is the shape type, but I don't think is enough to consider it different.

2022-10-27 06:44 UTC, matteobruni commented on glitter/js/404.js
> +    interactivity: {
This `interactivity` section is useless, please remove it.

2022-10-27 10:52 UTC, LeidiFlores commented
Ok, @matteobruni let me check

2022-10-31 02:10 UTC, LeidiFlores commented
hi @matteobruni ! 
I have a lot of problems with this MR, I'll close it and create another one, can I?

2022-10-31 07:06 UTC, matteobruni commented
> hi @matteobruni !
> I have a lot of problems with this MR, I'll close it and create another one, can I?

Yes no problem

2022-10-31 16:18 UTC, closed without merging